from typing import Optional
from pydantic import BaseModel

class NotificationSchema(BaseModel):
    user_id: int
    waitlist_entry_id: int
    message: str
    status: str = "pending"
    # generated by DB, only used in output
    created_at: Optional[str] = None
    # optional until sent
    sent_at: Optional[str] = None

    class Config:
        orm_mode = True
